# Generated by Django 4.0.6 on 2022-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.TextField()),
                ('gruppe', models.TextField()),
                ('mandag', models.TextField(blank=True)),
                ('tirsdag', models.TextField(blank=True)),
                ('onsdag', models.TextField(blank=True)),
                ('torsdag', models.TextField(blank=True)),
                ('fredag', models.TextField(blank=True)),
                ('pligter', models.TextField(blank=True)),
            ],
        ),
    ]
