# Generated by Django 4.0.6 on 2022-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.TextField()),
                ('tlf', models.TextField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('arbejde', models.TextField(blank=True)),
            ],
        ),
    ]
